- hosts: master 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
  vars:
     add_user: true
     generate_key: true
     install_hadoop: true
     install_firewall: false
     open_firewall: false
     disable_firewall: false
     config_hadoop: true
     start_hadoop: true
     ansible_os_family: 'RedHat'
  roles:
    - user
    - fetch_public_key
    - authorized
    - java
    - hadoop
