---
- name: Copy spark-env.sh
  template: src=spark-env.sh dest={{ spark_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy spark-defaults.conf
  template: src=spark-defaults.conf dest={{ spark_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy log4j.properties
  template: src=log4j.properties dest={{ spark_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Spark Env Script
  template: src=spark_env.sh dest=/etc/profile.d/ mode=755

- name: Set Hive Env
  shell: bash /etc/profile.d/spark_env.sh